import { stage1 } from './stages/stage1.js';
import { stage2 } from './stages/stage2.js';
import { stage3 } from './stages/stage3.js';
import { stage4 } from './stages/stage4.js';

export const roomConfigs = {
  pilotCabin: {
    id: 'pilotCabin',
    name: "Pilot's Cabin",
    color: '#6aa8ff',
    imageKey: 'pilotCabin',
    left: null,
    right: 'clinic',
    up: null,
    down: null,
    gridPos: { col: 0, row: 0 },
    stage: 1,
    hotspots: [
      {
        id: 'pilot-chat',
        label: 'Message screen',
        x: '18%',
        y: '32%',
        w: '2%',
        h: '2%',
        objective: 'pilot-chat',
        content: stage1.chatChoice,
      },
      {
        id: 'pilot-planets',
        label: 'Window and planet posters',
        x: '55%',
        y: '29%',
        w: '2%',
        h: '2%',
        objective: 'pilot-planets',
        content: stage1.planetChoice,
      },
      {
        id: 'pilot-roster',
        label: 'Crew roster',
        x: '78%',
        y: '29%',
        w: '2%',
        h: '2%',
        objective: 'pilot-roster',
        content: stage1.rosterChoice,
      },
      {
        id: 'pilot-dispenser',
        label: 'Liquid dispenser',
        x: '10%',
        y: '69%',
        w: '2%',
        h: '2%',
        objective: 'pilot-dispenser',
        content: stage1.dispenserChoice,
      },
      {
        id: 'pilot-bed-label',
        label: 'Bed label',
        x: '61%',
        y: '74%',
        w: '2%',
        h: '2%',
        requiresObjectives: ['pilot-chat', 'pilot-planets'],
        objective: 'pilot-bed-label',
        content: stage1.bedLabelClue,
      },
      {
        id: 'pilot-door',
        label: 'Cabin door lock',
        x: '91%',
        y: '44%',
        w: '2%',
        h: '2%',
        requiresObjectives: [
          'pilot-chat',
          'pilot-planets',
          'pilot-roster',
          'pilot-dispenser',
          'pilot-bed-label',
        ],
        objective: 'stage1-complete',
        content: stage1.doorBuilder,
      },
    ],
  },
  clinic: {
    id: 'clinic',
    name: 'Clinic',
    color: '#70d99d',
    imageKey: 'clinic',
    left: 'pilotCabin',
    right: 'lab',
    up: null,
    down: null,
    gridPos: { col: 1, row: 0 },
    stage: 2,
    unlockedBy: 'stage1-complete',
    hotspots: [
      {
        id: 'clinic-sign',
        label: 'Clinic sign',
        x: '18%',
        y: '17%',
        w: '2%',
        h: '2%',
        objective: 'clinic-sign',
        content: stage2.signChoice,
      },
      {
        id: 'clinic-medic',
        label: 'Medic screen',
        x: '37%',
        y: '36%',
        w: '2%',
        h: '2%',
        objective: 'clinic-medic',
        content: stage2.medicChoice,
      },
      {
        id: 'clinic-photos',
        label: 'Treatment wall',
        x: '61%',
        y: '31%',
        w: '2%',
        h: '2%',
        objective: 'clinic-photos',
        content: stage2.photosChoice,
      },
      {
        id: 'clinic-medicine',
        label: 'Medicine shelf',
        x: '82%',
        y: '28%',
        w: '2%',
        h: '2%',
        objective: 'clinic-medicine',
        content: stage2.medicineChoice,
      },
      {
        id: 'clinic-refill',
        label: 'Refill machine',
        x: '81%',
        y: '67%',
        w: '2%',
        h: '2%',
        objective: 'clinic-refill',
        content: stage2.refillChoice,
      },
    ],
  },
  lab: {
    id: 'lab',
    name: 'Lab / Factory',
    color: '#e3d85c',
    imageKey: 'lab',
    left: 'clinic',
    right: 'commsRoom',
    up: null,
    down: null,
    gridPos: { col: 2, row: 0 },
    stage: 3,
    unlockedBy: 'stage2-complete',
    hotspots: [
      {
        id: 'lab-sign',
        label: 'Lab sign',
        x: '18%',
        y: '16%',
        w: '2%',
        h: '2%',
        objective: 'lab-sign',
        content: stage3.signChoice,
      },
      {
        id: 'lab-logs',
        label: 'System logs',
        x: '35%',
        y: '34%',
        w: '2%',
        h: '2%',
        objective: 'lab-logs',
        content: stage3.logsSequence,
      },
      {
        id: 'lab-machine',
        label: 'Manufacturing machine',
        x: '52%',
        y: '48%',
        w: '2%',
        h: '2%',
        requiresObjectives: ['lab-sign', 'lab-logs'],
        objective: 'lab-machine',
        content: stage3.machineBuilder,
      },
      {
        id: 'lab-destination',
        label: 'Destination map',
        x: '75%',
        y: '34%',
        w: '2%',
        h: '2%',
        requiresObjectives: ['lab-machine'],
        objective: 'lab-destination',
        content: stage3.destinationBuilder,
      },
      {
        id: 'lab-comms',
        label: 'Communication door',
        x: '90%',
        y: '39%',
        w: '2%',
        h: '2%',
        requiresObjectives: ['lab-machine', 'lab-destination'],
        objective: 'lab-comms',
        content: stage3.commsBuilder,
      },
    ],
  },
  commsRoom: {
    id: 'commsRoom',
    name: 'Bridge / Comms',
    color: '#b58cff',
    imageKey: 'commsRoom',
    left: 'lab',
    right: null,
    up: null,
    down: null,
    gridPos: { col: 3, row: 0 },
    stage: 4,
    unlockedBy: 'stage3-complete',
    hotspots: [
      {
        id: 'bridge-commander',
        label: 'Commander channel',
        x: '50%',
        y: '34%',
        w: '2%',
        h: '2%',
        objective: 'stage4-complete',
        content: stage4.commanderConversation,
      },
    ],
  },
};

export const startingRoom = 'pilotCabin';
